<a href="https://colab.research.google.com/github/ugoetudo/sequence-labeler/blob/main/TBOFullInference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from transformers import AutoTokenizer, TFRobertaModel
import tensorflow as tf
import pandas as pd
import numpy as np
from google.colab import drive
from tqdm import tqdm
from tqdm.auto import tqdm
import keras
import random
from itertools import combinations
from keras import layers
from sklearn.model_selection import train_test_split
import json
from keras import regularizers
import spacy
!python -m spacy download 'en_core_web_md'
keras.config.disable_traceback_filtering()

Collecting en-core-web-md==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.7.1/en_core_web_md-3.7.1-py3-none-any.whl (42.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 54.9 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /usr/local/lib/python3.11/dist-packages (from en-core-web-md==3.7.1) (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.10.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.5.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2025.1.31)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-md==3.7.1) (0.1.2)
Installing collected packages: en-core-web-md
Successfully installed en-core-web-md-3.7.1
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [2]:
pd.options.display.max_columns = 80
pd.options.display.max_rows = 700

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
tokenizer = AutoTokenizer.from_pretrained("FacebookAI/roberta-base",
                                          add_prefix_space=True,
                                          clean_up_tokenization_spaces=True)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [5]:
NICKNAME = "breakthroughs_ner_tr_first_anno"
final_sequences = pd.read_csv(f"/content/drive/MyDrive/Colab Data/{NICKNAME}.csv")
final_sequences = final_sequences.rename(columns={"BIO_first":"target_BIO"})
NICKNAME = "ner_rand_all_types"
unique_tags = final_sequences['target_BIO'].unique().tolist()
tag2idx = {t: i for i, t in enumerate(unique_tags)}
idx2tag = {k:v for v,k in tag2idx.items()}
pad_tag = 72
idx2tag[pad_tag] = 'B-O'

In [6]:
@keras.saving.register_keras_serializable()
class TransformerBlock(layers.Layer):
  def __init__(self, embed_dim,
               num_heads,
               feed_forward_dim,
               max_len,
               dr_rate=0.0,
               train_mode=False,
               ):
    super().__init__()
    self.max_len = max_len
    self.train_mode = train_mode
    self.embed_dim = embed_dim
    self.num_heads = num_heads
    self.feed_forward_dim = feed_forward_dim
    self.dr_rate = dr_rate
    self.attention = layers.MultiHeadAttention(self.num_heads, key_dim=self.embed_dim)
    self.norm1 = layers.LayerNormalization(epsilon=1e-6)
    self.norm2 = layers.LayerNormalization(epsilon=1e-6)
    self.ff1 = layers.Dense(self.feed_forward_dim, activation="relu")
    self.ff2 = layers.Dense(self.embed_dim)
    self.dropout1 = layers.Dropout(self.dr_rate)
    self.dropout2 = layers.Dropout(self.dr_rate)

  def build(self, input_shape=None):
    if not self.ff1.built:
      self.ff1.build((self.max_len, self.embed_dim))
    if not self.ff2.built:
      self.ff2.build((self.max_len, self.feed_forward_dim))
    if not self.attention.built:
      self.attention.build([self.max_len, self.num_heads, self.embed_dim],
                           [self.max_len, self.num_heads, self.embed_dim])

  def get_config(self):

    return {"embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "feed_forward_dim": self.feed_forward_dim,
            "dr_rate": self.dr_rate,
            "train_mode":False}

  def call(self, inputs):
    attn_output = self.attention(*inputs)
    attn_output = self.dropout1(attn_output, training=self.train_mode)
    out1 = self.norm1(inputs[0] + attn_output)
    ffn_output = self.ff1(out1)
    ffn_output = self.ff2(ffn_output)
    ffn_output = self.dropout2(ffn_output, training=self.train_mode)
    ln2 = self.norm2(out1 + ffn_output)
    return ln2

@keras.saving.register_keras_serializable()
class robertaTransformerModel(keras.Model):
  def __init__(self,
               feed_forward_dim,
               num_tags,
               roberta_out="",
               train_mode=True,
               roberta_path="/content/drive/MyDrive/Colab Data/roberta-base",
               num_heads=5,
               max_len=80,
               **kwargs):
    super().__init__(**kwargs)
    self.max_len = max_len
    self.num_heads = num_heads
    self.roberta_path = roberta_path
    self.distilbert = TFRobertaModel.from_pretrained(self.roberta_path, name='roberta')
    self.roberta_out = roberta_out
    self.train_mode = train_mode
    self.num_tags = num_tags
    self.feed_forward_dim = feed_forward_dim
    self.dropout2 = layers.Dropout(0.2)
    self.transformer_block = TransformerBlock(self.distilbert.config.hidden_size,
                                              self.num_heads,
                                              self.distilbert.config.hidden_size,
                                              self.max_len,
                                              train_mode=self.train_mode)
    self.ffn = layers.Dense(self.feed_forward_dim, activation="relu", name="ffn")
    self.out = layers.Dense(self.num_tags, activation="softmax", name="out")

    self.distilbert.trainable = train_mode

  def build(self, input_shape=None):
    with tf.name_scope(self.distilbert.name):
      self.distilbert.build(None)
    if not self.transformer_block.built:
      self.transformer_block.build(input_shape=None)
    if not self.ffn.built:
      self.ffn.build((self.max_len, self.distilbert.config.hidden_size))
    if not self.out.built:
      self.out.build((self.max_len, self.feed_forward_dim))
    super().build(input_shape=None)

  def get_config(self):
    config = super().get_config()
    config.update({"feed_forward_dim": self.feed_forward_dim,
                   "num_tags": self.num_tags,
                   "train_mode": False,
                   "num_heads": self.num_heads,
                   "max_len": self.max_len,
                   "roberta_path": self.roberta_out})
    return config

  @classmethod
  def from_config(cls, config):
    return cls(**config)

  def call(self, inputs):
    encoded = self.distilbert(**inputs,
                        training=self.train_mode)
    x = encoded[0]
    if self.train_mode:
      x = self.dropout2(x)

    x = self.transformer_block((x,x))
    x = self.ffn(x) # last hidden state
    x = self.out(x)
    return x

  def save(self, filepath, overwrite=True, include_optimizer=True, save_format=None, signatures=None, options=None, **kwargs):

      print("Saving fine-tuned roberta model...")
      self.distilbert.save_pretrained(self.roberta_out)

      print("Saving keras model...")
      super().save(filepath, overwrite=True, **kwargs)

  def compile(self, model_optimizer, loss, metrics):
    super().compile(optimizer=model_optimizer, loss=loss, metrics=metrics)
    self.model_optimizer = model_optimizer
    self.loss = loss
    self.loss_metrics = metrics

  def get_compile_config(self):
    return {
        "model_optimizer": self.model_optimizer,
        "loss": self.loss,
        "metrics": self.loss_metrics
    }

  def compile_from_config(self, config):
    optimizer = keras.utils.deserialize_keras_object(config.get("model_optimizer"))
    loss = keras.utils.deserialize_keras_object(config.get("loss"))
    metrics = [keras.utils.deserialize_keras_object(metric) for metric in config.get("metrics")]
    self.compile(optimizer, loss, metrics)

In [7]:
def predict_from_string(test_sent, model, tokenizer, idx2tag):
  tokeinzed_sentence = tokenizer(test_sent, truncation=True,
            padding=True, max_length=saved_model.get_config()['max_len'],
            return_tensors="tf")
  decoded = tokenizer.convert_ids_to_tokens(tokeinzed_sentence['input_ids'][0])
  decoded = [tk[1:] if tk.find("Ġ") == 0 else tk for tk in decoded]
  pred = model.predict(dict(tokeinzed_sentence))
  pred = pred.argmax(axis=2)
  pred = [[idx2tag[i] for i in seq] for seq in pred]
  return pred, decoded, tokeinzed_sentence

In [8]:
def normalize_predictions(pred, decoded, tk_sent, single_pred=True):
  wids = tk_sent.word_ids()
  recon = []
  curr_pred = []
  last_wid = None
  for i in range(len(wids)):
    if wids[i] is None:
      last_wid = 1
      continue
    if last_wid is None:
      last_wid = wids[i]
    if last_wid != wids[i]:
      recon.append(decoded[i])
      curr_pred.append([pred[0][i]])
      last_wid = wids[i]
    else:
      last_recon = recon.pop()
      recon.append(last_recon + decoded[i])
      curr_pred[-1].append(pred[0][i])
      last_wid = wids[i]
  if single_pred:
    curr_pred = [list(set(item))[0] for item in curr_pred]
    curr_pred = ["O" if item == "B-O" else item for item in curr_pred]
  else:
    curr_pred = [list(set(item)) for item in curr_pred]
  assert len(curr_pred) == len(recon)
  return curr_pred, recon

In [9]:
# Credit to Priyankar Bose for the code in this cell

def setup_relationship_extraction(tokens, entity_tags):
    # Ensuring that the length of tokens and entities match
    if len(tokens) != len(entity_tags):
        raise ValueError("The lengths of tokens and entity_tags must match.")

    relationship_data = []
    sentence_text = " ".join(tokens).replace("<s> ", "")  # Ignoring <s> (space)
    # Generating a random sentence ID
    sentence_id = random.randint(1000, 9999)

    # Generating token IDs array starting from 0
    tkids = list(range(len(tokens)))

    # Nested function to extract entities from tokens and tags
    def extract_entities(tokens, tags, tkids):
        entities = []
        current_entity = []
        current_entity_type = None
        current_entity_ids = []

        for token, tag, tkid in zip(tokens, tags, tkids):
            if tag.startswith("B-") or (tag.startswith("I-") and current_entity_type != tag[2:]) :  # Beginning of a new entity
                if current_entity:  # Save the previous entity
                    entities.append((" | ".join(map(str, current_entity_ids)), current_entity_type, " ".join(current_entity)))
                # Start a new entity
                current_entity = [token]
                current_entity_type = tag[2:]  # Entity type
                current_entity_ids = [tkid]
            elif tag.startswith("I-") and current_entity_type == tag[2:]:  # Continuation of the same entity
                current_entity.append(token)
                current_entity_ids.append(tkid)
            elif tag == "O" and current_entity:  # Ignoring "O" but continue the current entity
                continue
            else:  # Outside of an entity
                if current_entity:  # Save the previous entity
                    entities.append((" | ".join(map(str, current_entity_ids)), current_entity_type, " ".join(current_entity)))
                current_entity = []
                current_entity_type = None
                current_entity_ids = []

        # Add the last entity if present
        if current_entity:
            entities.append((" | ".join(map(str, current_entity_ids)), current_entity_type, " ".join(current_entity)))

        return entities

    # Extracting entities
    entities = extract_entities(tokens, entity_tags, tkids)

    # Generating all combinations of two entities with direction (left, right)
    for left, right in combinations(entities, 2):
        left_entity_ids, left_entity_type, left_full_text = left
        right_entity_ids, right_entity_type, right_full_text = right

        # Creating a relationship entry for left-to-right direction
        relationship_data.append({
            "sid": sentence_id,
            "lefttkids": left_entity_ids,
            "righttkids": right_entity_ids,
            "sentence_text": sentence_text,
            "left_entity": left_entity_type,
            "lefttext": left_full_text,
            "right_entity": right_entity_type,
            "righttext": right_full_text
        })

        # Creating a relationship entry for right-to-left direction
        relationship_data.append({
            "sid": sentence_id,
            "lefttkids": right_entity_ids,
            "righttkids": left_entity_ids,
            "sentence_text": sentence_text,
            "left_entity": right_entity_type,
            "lefttext": right_full_text,
            "right_entity": left_entity_type,
            "righttext": left_full_text
        })

    return relationship_data

In [10]:
MAX_ENTITY_LENGTH = 5
MAX_SENTENCE_LEN = 100
with open("/content/drive/MyDrive/Colab Data/entity_lookup_rels.json", "r") as ent_lookup_file:
  entity_lookup = json.load(ent_lookup_file)

def make_pos_embs_l(x):
  entity_vec = np.zeros(MAX_SENTENCE_LEN)
  tkids = str(x['lefttkids']).replace(" ", "").split("|")
  tkids = [int(tk) for tk in tkids]
  entity_vec[tkids] = entity_vec[tkids] + entity_lookup[x['left_entity']]
  entity_vec[0] = 1 #encodes the left or the right
  return entity_vec

def make_pos_embs_r(x):
  entity_vec = np.zeros(MAX_SENTENCE_LEN)
  tkids = str(x['righttkids']).replace(" ", "").split("|")
  tkids = [int(tk) for tk in tkids]
  entity_vec[tkids] = entity_vec[tkids] + entity_lookup[x['right_entity']]
  entity_vec[0] = 2 #encodes the left or the right
  return entity_vec

def get_entity_start_l(x):
  tkids = str(x['lefttkids']).replace(" ", "").split("|")
  tkids = [int(tk) for tk in tkids]
  rtkids = str(x['righttkids']).replace(" ", "").split("|")
  rtkids = [int(tk) for tk in rtkids]
  if rtkids[0] > tkids[0]:
    return tkids[0]
  else:
    return tkids[-1]

def get_entity_start_r(x):
  tkids = str(x['righttkids']).replace(" ", "").split("|")
  tkids = [int(tk) for tk in tkids]
  ltkids = str(x['lefttkids']).replace(" ", "").split("|")
  ltkids = [int(tk) for tk in ltkids]
  if ltkids[0] > tkids[0]:
    return tkids[0]
  else:
    return tkids[-1]

def slice_sentence(x):
  ls = x["l_entity_start"]
  rs = x["r_entity_start"]
  if rs > ls:
    s_slice = x["sentence_text"][ls:rs]
  else:
    s_slice = x["sentence_text"][rs:ls]
  return s_slice


def build_sentence_input(sentence_text):
  tokenized_sentence = tokenizer(sentence_text,
                                 max_length=MAX_SENTENCE_LEN,
                                 truncation=True,
                                 padding="max_length",
                                 is_split_into_words=True,
                                 return_tensors="tf"
                                 )
  # input_ids = tokenized_sentence["input_ids"]
  # attention_mask = tokenized_sentence["attention_mask"]
  return tokenized_sentence

In [11]:
@keras.saving.register_keras_serializable()
class TransformerBlock(layers.Layer):
  def __init__(self,
               embed_dim,
               num_heads,
               feed_forward_dim,
               max_len,
               dr_rate=0.25,
               train_mode=False):
    super().__init__()
    self.max_len = max_len
    self.embed_dim = embed_dim
    self.train_mode = train_mode
    self.num_heads = num_heads
    self.feed_forward_dim = feed_forward_dim
    self.dr_rate = dr_rate
    self.attention = layers.MultiHeadAttention(self.num_heads, key_dim=self.embed_dim)
    self.norm1 = layers.LayerNormalization(epsilon=1e-6)
    self.norm2 = layers.LayerNormalization(epsilon=1e-6)
    self.ff1 = layers.Dense(self.feed_forward_dim, activation="relu")
    self.ff2 = layers.Dense(self.embed_dim)
    self.dropout1 = layers.Dropout(self.dr_rate)
    self.dropout2 = layers.Dropout(self.dr_rate)

  def build(self, input_shape=None):
    if not self.ff1.built:
      self.ff1.build((self.max_len, self.embed_dim))
    if not self.ff2.built:
      self.ff2.build((self.max_len, self.feed_forward_dim))
    if not self.attention.built:
      self.attention.build([self.max_len, self.num_heads, self.embed_dim],
                           [self.max_len, self.num_heads, self.embed_dim])

  def get_config(self):

    return {"embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "feed_forward_dim": self.feed_forward_dim,
            "dr_rate": self.dr_rate}

  def call(self, inputs):
    attn_output = self.attention(*inputs)
    attn_output = self.dropout1(attn_output, training=self.train_mode)
    out1 = self.norm1(inputs[0] + attn_output)
    ffn_output = self.ff1(out1)
    ffn_output = self.ff2(ffn_output)
    ffn_output = self.dropout2(ffn_output, training=self.train_mode)
    ln2 = self.norm2(out1 + ffn_output)
    return ln2

@keras.saving.register_keras_serializable()
class valenceIntegratedModel(keras.Model):
  def __init__(self,
               feed_forward_dim,
               pos_emb_dim,
               rnn_hidden, #
               num_tags,
               num_valence,
               max_len,
               num_heads,
               train_mode,
               num_ents,
               dropout_rate=0.1,
               roberta_out="/content/drive/MyDrive/Colab Data/vire_fine_tuned/roberta_vire_embeddings",
               roberta_slice_out="/content/drive/MyDrive/Colab Data/vire_fine_tuned/roberta_slice_vire_embeddings",
               roberta_path="/content/drive/MyDrive/Colab Data/roberta-base",
               roberta_slice_path="/content/drive/MyDrive/Colab Data/roberta-base",
               **kwargs):
    super().__init__(**kwargs)
    self.training = train_mode
    self.dropout_rate = dropout_rate
    self.max_len = max_len
    self.train_mode = train_mode
    self.num_ents = num_ents
    self.feed_forward_dim = feed_forward_dim
    self.pos_emb_dim = pos_emb_dim
    self.rnn_hidden = rnn_hidden
    self.num_tags = num_tags
    self.num_heads = num_heads
    self.num_valence = num_valence
    self.roberta_path = roberta_path
    self.roberta_out = roberta_out
    self.roberta_slice_out = roberta_slice_out
    self.roberta = TFRobertaModel.from_pretrained(roberta_path,
                                                     trainable=self.train_mode,
                                                  name='roberta')
    self.roberta_slice = TFRobertaModel.from_pretrained(roberta_slice_path,
                                                        trainable=self.train_mode,
                                                        name='roberta_slice')
    self.droupout = layers.Dropout(self.dropout_rate)
    self.pos = layers.TimeDistributed(\
                              layers.Embedding(input_dim=num_ents,
                                               embeddings_regularizer=regularizers.L2(),
                                               output_dim=self.pos_emb_dim,
                                               trainable=self.train_mode))
    self.perm = layers.Permute((2,1,3))
    self.reshape = layers.Reshape((self.max_len, self.pos_emb_dim*2))
    self.dropout1 = layers.Dropout(self.dropout_rate)
    self.roberta_out = roberta_out
    self.transformer_block = TransformerBlock(self.roberta.config.hidden_size,
                                              self.num_heads,
                                              self.roberta.config.hidden_size,
                                              self.max_len,
                                              train_mode=self.train_mode,
                                              dr_rate=self.dropout_rate)
    self.pre_encoder = layers.Dense(self.roberta.config.hidden_size)
    self.rel_enc_trans = TransformerBlock(self.roberta.config.hidden_size,
                                              self.num_heads,
                                              self.roberta.config.hidden_size,
                                              self.max_len,
                                              train_mode=self.train_mode,
                                              dr_rate=self.dropout_rate)
    self.gmp = layers.GlobalMaxPooling1D()
    self.dnn_first = layers.Dense(self.feed_forward_dim, activation="relu")
    self.dnn_sec = layers.Dense(self.feed_forward_dim, activation="relu")
    self.dnn_third = layers.Dense(self.feed_forward_dim, activation="relu")
    self.out = layers.Dense(self.num_tags,
                            activation="softmax",
                            name='rel_out')
    self.valence_dnn1 = layers.Dense(self.feed_forward_dim,
                                     activation="relu")
    self.valence_out = layers.Dense(self.num_valence,
                                    activation="softmax",
                                    name='valence_out')

  def build(self):
    if not self.pos.built:
      self.pos.build(input_shape=(2, self.max_len, num_ents))
    with tf.name_scope(self.roberta.name):
      self.roberta.build(None)
    with tf.name_scope(self.roberta_slice.name):
      self.roberta_slice.build(None)
    if not self.transformer_block.built:
      self.transformer_block.build(input_shape=None)
    if not self.pre_encoder.built:
      self.pre_encoder.build((self.max_len,
                              self.roberta.config.hidden_size+(self.pos_emb_dim*2)))
    if not self.rel_enc_trans.built:
      self.rel_enc_trans.build(input_shape=None)
    if not self.dnn_first.built:
      self.dnn_first.build((1, self.roberta.config.hidden_size*2))
    if not self.dnn_sec.built:
      self.dnn_sec.build((1, self.feed_forward_dim))
    if not self.dnn_third.built:
      self.dnn_third.build((1, self.feed_forward_dim))
    if not self.out.built:
      self.out.build((1, self.feed_forward_dim))
    if not self.valence_dnn1.built:
      self.valence_dnn1.build((1, self.num_tags+self.feed_forward_dim))
    if not self.valence_out.built:
      self.valence_out.build((1, self.feed_forward_dim))
    # super().build(input_shape=None)

  def get_config(self):
    config = super().get_config()
    config.update({
        "feed_forward_dim": self.feed_forward_dim, # hyperopt
        "pos_emb_dim": self.pos_emb_dim, # hyperopt
        "rnn_hidden": self.rnn_hidden, # not used
        "num_tags": self.num_tags,
        "num_valence": self.num_valence,
        "num_ents": self.num_ents,
        "max_len": self.max_len,
        "dropout_rate": self.dropout_rate,
        "num_heads": self.num_heads, # hyperopt
        "train_mode": False,
        "roberta_out": self.roberta_out,
        "roberta_slice_out": self.roberta_slice_out,
        "roberta_path": self.roberta_out,
        "roberta_slice_path": self.roberta_slice_out,
    })
    return config

  @classmethod
  def from_config(cls, config):
    return cls(**config)

  def save(self, filepath, overwrite=True,
           include_optimizer=True, save_format=None,
           signatures=None, options=None, **kwargs):

      print("Saving fine-tuned roberta models...")
      self.roberta.save_pretrained(self.roberta_out)
      self.roberta_slice.save_pretrained(self.roberta_slice_out)
      print("Saving keras model...")
      super().save(filepath, overwrite=True, **kwargs)

  def call(self, inputs):
    # Begin relation encoder
    roberta_output = self.roberta(**inputs[0],
                                     training=self.train_mode)
    pos_embs = tf.stack([inputs[1], inputs[2]], axis=1)
    pos_embs = self.pos(pos_embs)
    pos_embs = self.perm(pos_embs)
    pos_embs = self.reshape(pos_embs)
    enc = layers.concatenate([roberta_output[0],
                              pos_embs],
                              axis=-1) #along the final axis
    enc = self.pre_encoder(enc)
    rnn_output = self.rel_enc_trans((enc, enc))
    if self.train_mode:
      enc = self.droupout(enc)
    # End relation encoder
    # Begin inner-context encoder
    enc_slice = self.roberta_slice(**inputs[3],
                                   training=self.train_mode)
    context_embeddings = self.transformer_block((enc_slice[0], enc))
    # End inner-context encoder
    inner_context = self.gmp(context_embeddings)
    rnn_output = self.gmp(rnn_output)
    rnn_output = layers.concatenate([rnn_output, inner_context], axis=-1)
    feed_forward_output = self.dnn_first(rnn_output)
    feed_forward_output = self.dnn_sec(feed_forward_output)
    feed_forward_output = self.dnn_third(feed_forward_output)
    x = self.out(feed_forward_output)
    valence_out = self.valence_dnn1(layers.concatenate([x, feed_forward_output]))
    valence_out = self.valence_out(valence_out)
    return {"rel_out":x, "valence_out":valence_out}

In [12]:
NICKNAME = "ner_rand_all_types"
saved_model = keras.models.load_model(f"/content/drive/MyDrive/Colab Data/{NICKNAME}.keras", compile=False)
saved_model.summary()

All model checkpoint layers were used when initializing TFRobertaModel.

All the layers of TFRobertaModel were initialized from the model checkpoint at /content/drive/MyDrive/Colab Data/roberta_ner_embeddings_ner_rand_all_types.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaModel for predictions without further training.

Model: "roberta_transformer_model_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dropout (Dropout)                    │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ transformer_block (TransformerBlock) │ ?                           │      29,521,152 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ ffn (Dense)                          │ (80, 256)                   │         196,864 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ out (Dense)                          │ (80, 73)                    │          18,761 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 29,736,777 (113.44 MB)

 Trainable params: 29,736,777 (113.44 MB)

 Non-trainable params: 0 (0.00 B)

In [13]:
num_ents = len(entity_lookup.keys())+1
m = keras.models.load_model("/content/drive/MyDrive/Colab Data/valenced_re_integrated_att.keras", compile=False)
m.summary()

All model checkpoint layers were used when initializing TFRobertaModel.

All the layers of TFRobertaModel were initialized from the model checkpoint at /content/drive/MyDrive/Colab Data/vire_fine_tuned/roberta_vire_embeddings.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaModel for predictions without further training.
All model checkpoint layers were used when initializing TFRobertaModel.

All the layers of TFRobertaModel were initialized from the model checkpoint at /content/drive/MyDrive/Colab Data/vire_fine_tuned/roberta_slice_vire_embeddings.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaModel for predictions without further training.

Model: "valence_integrated_model_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dropout_4 (Dropout)                  │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed (TimeDistributed)   │ (2, 100, 67, 128)           │           8,576 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ permute (Permute)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ reshape (Reshape)                    │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_5 (Dropout)                  │ ?                           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ transformer_block_1                  │ ?                           │      20,074,752 │
│ (TransformerBlock)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (100, 768)                  │         787,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ transformer_block_2                  │ ?                           │      20,074,752 │
│ (TransformerBlock)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_max_pooling1d                 │ ?                           │               0 │
│ (GlobalMaxPooling1D)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (1, 256)                    │         393,472 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (1, 256)                    │          65,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (1, 256)                    │          65,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ rel_out (Dense)                      │ (1, 18)                     │           4,626 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (1, 256)                    │          70,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ valence_out (Dense)                  │ (1, 4)                      │           1,028 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 41,546,390 (158.49 MB)

 Trainable params: 41,537,814 (158.45 MB)

 Non-trainable params: 8,576 (33.50 KB)

In [36]:
from spacy.tokens.doc import Doc
nlp = spacy.load("en_core_web_md", disable=["lemmatizer", "ner"])
def spacy_rbt_tokenizer(text):
  tokeinzed_sentence = tokenizer(text, truncation=True,
            padding=True, max_length=saved_model.get_config()['max_len'],
            return_tensors="tf")
  decoded = tokenizer.convert_ids_to_tokens(tokeinzed_sentence['input_ids'][0])
  decoded = [tk[1:] if tk.find("Ġ") == 0 else tk for tk in decoded]
  decoded.pop()
  decoded = decoded[1:]
  return Doc(nlp.vocab, decoded)
nlp.tokenizer = spacy_rbt_tokenizer

In [24]:

def do_ner(test_sent, saved_model, tokenizer, idx2tag):
  pred, decoded, tk_sent = predict_from_string(test_sent, saved_model, tokenizer, idx2tag)
  norm_preds, recon_sent = normalize_predictions(pred, decoded, tk_sent)
  ner_viz = pd.DataFrame([norm_preds, recon_sent])
  relationship_data = setup_relationship_extraction(recon_sent, norm_preds)
  s_all_relations = pd.DataFrame(relationship_data)
  return s_all_relations, ner_viz

In [15]:
def do_relation_extraction(s_all_relations):
  s_all_relations["sentence_text"] = s_all_relations["sentence_text"].str.split(" ")
  s_all_relations['num_tokens'] = s_all_relations['sentence_text'].apply(len)
  s_all_relations["l_pos_embs"] = s_all_relations.apply(make_pos_embs_l, axis=1)
  s_all_relations["r_pos_embs"] = s_all_relations.apply(make_pos_embs_r, axis=1)
  s_all_relations["l_entity_start"] = s_all_relations.apply(get_entity_start_l, axis=1)
  s_all_relations["r_entity_start"] = s_all_relations.apply(get_entity_start_r, axis=1)
  s_all_relations["inner_context"] = s_all_relations.apply(slice_sentence, axis=1)
  l_pos_embs = tf.convert_to_tensor(np.stack(s_all_relations['l_pos_embs'].values))
  r_pos_embs = tf.convert_to_tensor(np.stack(s_all_relations['r_pos_embs'].values))
  sent_input = build_sentence_input(s_all_relations["sentence_text"].tolist())
  inner_context_input = build_sentence_input(s_all_relations["inner_context"].tolist())
  targets = ['Present', 'none', 'Cooperates', 'Informs', 'Is',
           'Opposes', 'Agrees', 'Threat', 'Belongs',
           'MovesFor', 'Thinks', 'Caused', 'IsNot', 'Obtains',
           'Disagrees', 'Influences', 'Harms', 'Kills']
  rel_target_encoding = {target: i for i, target in enumerate(targets)}

  v_target_encoding = {v_target: i for i, v_target in enumerate(['Neutral',
                                                                'Negative',
                                                                'Positive',
                                                                'none'])}
  cr_targets = {v:k for k,v in rel_target_encoding.items()}
  cv_targets = {v:k for k, v in v_target_encoding.items()}
  lps = m.predict([
                    dict(sent_input),
                    l_pos_embs,
                    r_pos_embs,
                    dict(inner_context_input)
                  ],
                  batch_size=32)
  vp = lps['valence_out'].argmax(axis=1)
  rp = lps['rel_out'].argmax(axis=1)

  s_all_relations['pred_rel'] = rp
  s_all_relations['pred_rel'] = s_all_relations['pred_rel'].map(cr_targets)
  s_all_relations['pred_val'] = vp
  s_all_relations['pred_val'] = s_all_relations['pred_val'].map(cv_targets)
  s_all_relations = s_all_relations.sort_values(by='sid')[["sid","sentence_text",
                                                           "lefttext","righttext",
                                                           "pred_rel", "pred_val"]]
  return s_all_relations

In [16]:
def get_nodes_from_batch(sents_batch):
  all_nodes = pd.DataFrame(columns=["sid", "sentence_text", "lefttext", "righttext", "pred_rel", "pred_val"])
  ner_visuals = pd.DataFrame(columns=[f"t{i}" for i in range(80)])
  for test_sent in sents_batch:
    s_all_relations, ner_visual = do_ner(test_sent, saved_model, tokenizer, idx2tag)
    ner_visual = ner_visual.rename(columns={i:f"t{i}" for i in range(80)})
    if s_all_relations.shape[0] > 0:
      extracted_nodes = do_relation_extraction(s_all_relations)
    else:
      print("No Relations Found")
      extracted_nodes = pd.DataFrame(columns=["sid", "sentence_text", "lefttext", "righttext", "pred_rel", "pred_val"])
    all_nodes = pd.concat([all_nodes, extracted_nodes])
    ner_visuals = pd.concat([ner_visuals, ner_visual])
  return all_nodes, ner_visuals

In [17]:
test_sents = ["Elon Musk is an overt white supremacy and nazism from a fascist who grew up in apartheid South Africa.",
"Tariffs on Canada, Mexico and China are a cudgel to force those countries, America's largest trading partners, to crack down on the flow of drugs and migrants into the United States.",
"Russian oligarchs have hidden their money in London for twenty years, encouraged by British bankers, lawyers and politicians.",
"Surely you could have picked a pundit who hasn't been parroting white supremacist talking points so much that he's Richard Spencer's favorite TV personality.",
"Amazon pulled out of New York before they pulled out of advertising on Breitbart",
"Shopify has blocked us for pointing out that he helps sites like Breitbart monetize bigotry by selling their merchandise and his argument for doing it is free speech.",
"Very strange what happens when you bag on diversity and inclusion every night when your show is sponsored by companies that have pages on their websites touting diversity and inclusion.",]

In [18]:
raw_sample = pd.read_csv('/content/drive/MyDrive/Colab Data/sg_tl_sample.csv')
raw_sample['samples'] = raw_sample['samples'].str.replace("Ã¢â‚¬â„¢", "'")
raw_sample['samples'] = raw_sample['samples'].str.replace("Ã¢â‚¬Å“", "'")
raw_sample['samples'] = raw_sample['samples'].str.replace("Ã¢â‚¬Â", "'")
raw_sample['samples'] = raw_sample['samples'].str.replace("http", " http")
raw_sample['samples'] = raw_sample['samples'].str.replace("Ã¢Â\x81Â¦", "")
raw_sample['samples'] = raw_sample['samples'].str.replace("Ã¢Â\x81Â©", "")
raw_sample['samples'] = raw_sample['samples'].str.replace("\x9d", "")
raw_sample['samples'] = raw_sample['samples'].str.split("http")
raw_sample['samples'] = raw_sample['samples'].apply(lambda x: x[0])
raw_sample['samples'] = raw_sample['samples'].str.split("pic.")
raw_sample['samples'] = raw_sample['samples'].apply(lambda x: x[0])
test_sents = raw_sample['samples'].values.tolist()
test_sents

["That is your prerogative if you want to support him, but there are plenty of other great people who will fight for everyone's rights who haven't ever considered wearing blackface.",
 "None of these dudes can ever believe they're being called on their shit.",
 'Everyone deserves to be given a chance to change, but how can someone who, as an adult, dressed in one of the worst, if not the worst stereoty',
 "2019: The year that actual photos and video have somehow ceased to be what you're actually looking at.",
 "Real talk. Who among us hasn't chosen a photo of two people we did not know wearing blackface and a KKK costume for our yearbook page? ",
 "Okay, how about this one? It's a pattern, man. It's not a one off. ",
 'Agreed! Now do Steve King. ',
 "LOL! You're so nice, but NO THANKS!",
 'Reminder that there are far more insidious types of racism in politics than an old photo and all of it, including the guy in the old photo, needs to go.',
 "That's what he did.",
 'No, the implication, IMHO, is that anyone whose judgement allowed them to be in that photo can rightfully govern a state that has a sizable (or really any) population that holds those tropes to be the most offensive there are.',
 'Sounds good. Have a great day.',
 "This is a dishonest argument. If you're Black and you hear someone on the air say the N word, that's not a little thing. Do yourself a favor and watch Ice Cube's argument to him and get back to us here.",
 "Plenty of people can argue for political policies without saying these things. Just because you agree with him doesn't change the fact that he's been racist on the air more than a few times. It's not a one-off deal.",
 'When you have to check if you were the guy in blackface or the guy in the Klan hood...',
 "He might 'rock', but he also drops the N word on his telecast on occasion and he seems to not have a problem with being casually racist on the air.",
 'Great minds, friend. Great minds.',
 "Nope. You just kind of have to rely on a network not being cool with a show's repeated racism. Which you'd think wouldn't be that hard.",
 'Imagine having the ability to ',
 'He did it again, folks. How long is @HBO going to be cool with a guy being unabashedly racist on their network under the guise of just being outrageous? ',
 "Okay, more the a hundred. Man, everyone's SO literal around here.",
 "Steve King is going to endorse Ralph Northam, isn't he? ",
 'Now go back in time and deliver this on the campaign trail.',
 'Not equating those two politicians. Equating the thoughts of some outlets and individuals on this platform that suddenly have a problem with racism after defending King for years.',
 "It's not a comparison. Pointing out that some outlets who have been staunch defenders of King's suddenly have a massive problem with racism, which he espouses on the regular.",
 'There are also a lot of people on here who had a problem with Megyn Kelly defending blackface that are making excuses for Northam. Consistency matters.',
 "Whole lot of people on here clutching pearls over Northam that were defending Steve King for years. You either have a problem with racism or you don't.",
 '2019',
 "He's the one who put it on his yearbook page.",
 'Indeed.',
 'DISCLAIMER: This should not have to be a new rule.',
 "Apparently we haven't!",
 'NEW RULE: No blackface.',
 'Do not pass go. Do not collect $100. RESIGN. ',
 "To all of our New England-loving followers, we're sorry. We love you.",
 'Gab: We welcome all of our hundreds of thousands of new users to express themselves freely! Also Gab: Sorry to the six people who have applied to join our free speech platform. We cannot allow you to speak your mind at this time. ',
 'Go Rams.',
 '...has nothing to do with a company hosting a podcast.',
 'Welcome back. You know who was still here while you were suspended? Real, actual Nazis.',
 'Man oh man. This is real. Just saw it on @iTunes. Hey @AppleSupport, sure this is an oversight, but you have a literal Nazi podcast on your platform. ',
 'Cool platform @Jack. ',
 'Wow. ',
 'Sorry about the snoring.',
 "And if that won't work, just get rid of all of us and start this whole thing over.",
 "FREE IDEA FOR @jack: Get rid of ALL of the bots, then you don't have to do this every couple of weeks. ",
 'Still dealing with Nazis on here. Thanks for asking!',
 'Happy to have gotten one more tweet in last night before the official decree.',
 'Good stuff. ',
 'And at what point do advertisers decide enough is enough? They are footing the bill for everything that @facebook does. They could all walk away and likely be just fine. ',
 '',
 "Kaitlin Bennett is the Tomi Lahren of Ann Coulters and don't pretend this isn't a perfect tweet.",
 'Wait, how much tax could you possibly pay from the $127 in annual donations to your Patreon account?',
 'CONFIRMED: @creditsesame will no longer advertise on Tucker Carlson Tonight. ',
 'Always Be Grifting ',
 'This is just really, really good. Well done.',
 "So essentially, she's just putting on high school plays now?",
 'Just today, just today.',
 "Nothing's ever going to change, is it? ",
 "Wait, you don't weep uncontrollably all day?",
 'This is our surprised face. ',
 'This is important, folks. ',
 'Ã‚Â¯\\_(Ã£Æ’â€ž)_/Ã‚Â¯',
 "Lord Voldemort. It's Lord Voldemort, right? ",
 'CONFIRMED: @TSCTA has blocked Breitbart from their media buy! Many thanks! ',
 'CONFIRMED:  @PennLPSOnline has blocked Breitbart from their media buy! Thanks so much!',
 'CONFIRMED: @baronfig has blocked Breitbart from their media buy! Many thanks! ',
 "This is the second story in the last week that shows @Facebook taking advantage of kids. Kids! Why the fuck aren't they being investigated like every single day of the week right now?? ",
 "And I should add that I'm still far more intelligent than this clown.",
 "I'm an advertising executive and most of the journalists I know are much smarter than me. ",
 "Several years later and @Twitter, @facebook & @YouTube are no closer to solving their disinformation and bot problems. And that's with immense pressure. Without competition, the threat of regulation or advertisers demanding change, there's no reason for them to change a thing. ",
 'Man, @youtube is awful. ',
 "Imagine for a second if these two people were Black, Brown or Muslim. Fox News, Breitbart and The Daily Caller would talk about this for a month. Bet you ten bucks it won't even warrant more than an article or a single segment. ",
 '',
 "When Tucker Carlson said that immigrants make our country 'dirtier', he lost 15+ advertisers. Now he's pushing the idea that they're 'diseased'. If you're an advertiser, this is all the proof you need to see that Fox News doesn't care about your brand. ",
 'SureJan.gif ',
 "It's almost like @facebook does not want to fix their advertising problems. ",
 'This opinion is  @verified.',
 'CONFIRMED: @CaciqueInc has blocked Breitbart from their media buy! Thanks so much! ',
 'Who knew it would be so hard to keep people working on a show that openly espouses bigotry every week? ',
 'FIX YOUR SHIT, @twittersafety! ',
 'CONFIRMED: @kpthrive (Kaiser Permanente) has blocked Breitbart from their media buy. Many thanks! ',
 "Apparently, Brokaw has apologized for this statement, but it's safe to say that editorial like this on major networks doesn't help the country. It should also be said that this is the same kind of content that is said every night on Fox with the full backing of the network.",
 'Nah. ',
 'CONFIRMED: @acefitness will block Breitbart from their media buy! Thanks so much! ',
 'The Gorilla Change of Mindset',
 'CONFIRMED: @receptionistapp will block Breitbart from their media buy! Many thanks! ',
 'This thread is wild. The fact that white supremacists and Holocaust deniers view Breitbart as a recruitment tool obviously says something about the site, but @disqus and owners @ZetaGlobal allow this despite their Terms of Service is truly disgusting. ',
 'Unfortunately, @twittersafety has no desire to stop harassment. To them, engagement is engagement. The business model is antithetical to the idea of policing their platform. ',
 "Breitbart printed an article about #holocaustrembranceday today. Looks like they've deleted dozens of comments by their readership. These were left up, though. They can print all the articles they want, but they cannot escape what they've created.",
 'Remember when you were asked for five days to take this comment threatening my son at our old synagogue off of your website and you did nothing?',
 "Cool, but we haven't.",
 "There's a new trend on here amongst the 'free speech' crowd to call pretty much anything that's said about them 'defamatory' and it's fucking hysterical.",
 "Why is is funny that brands don't want to associate with racist, sexist articles, Seth? 4,100 advertisers have already determined that this type of content doesn't match their brand values. ",
 'CONFIRMED: @GustoHQ has blocked Breitbart from their media buy! Many thanks! ',
 'Hello, @kpthrive. Does this mean you have removed yourselves from this site? Over 4,100 advertisers already have done so. Please let us know if you do!',
 'CONFIRMED: @SportDOGBrand has blocked Breitbart from their media buy. Many thanks! ',
 'CONFIRMED: @VINEXPO has blocked Breitbart from their media buy! Thanks so much! ',
 "Being off Twitter for two days makes you realize how much you'd appreciate being off Twitter forever.",
 "You're right, Erick. They should have definitely all gone to outlets like Breitbart and The Daily Caller to write fake articles vilifying brown people, women and the gay community to serve the interests of their billionaire benefactors instead.",
 "Weird. The day also shows down when getting harassed, doxxed and dealing with racist epithets on the platform you created while you're busy doing crap like this.",
 "No one watches the switch on 4Chan, making it as easy as ever to organize campaigns of harassment and death threats. It is @TwitterSafety, though, that continues to show the world that they're ill prepared for these onslaughts, ensuring they'll continue unabated on this platform. ",
 "They shouldn't. That would be colossally stupid. Kind of like this op-ed.",
 'Advertisers have always supported programming that reflects their brands and appeal to as many consumers as possible. Why should they be obligated to support shows that actively divide people on the basis of race, gender and immigration status?',
 "According to this, the answer is that advertisers should just continue to support everything. Why don't they just place ads on The Daily Stormer, then? Why aren't there advertisers on 4Chan? How come they're not clamoring for airtime on Infowars?",
 "This person is supposed to be in advertising and yet doesn't seem to understand the simple concept that advertisers don't want to support things that don't reflect their brand values. By conflating it with politics, he gives cover to the bigotry that's featured on these shows.",
 "Advertisers leave these shows because many of them are racist or sexist, pure and simple. None of these brands want to be associated with a show that says immigrants make our country 'dirtier' or that women's advancement causes higher rates of incarceration and alcoholism.",
 "THREAD: This is what we like to call around here 'hot garbage'. First, it loses everyone the instant that it compares advertisers leaving shows with highly divisive overtones to the 'Red Scare'. And yet, somehow, some way, it gets dumber from there. ",
 "Anyone who threatens anyone else on these platforms should be removed. Party shouldn't matter.",
 "When people talk about the social platforms' removal of those who violate their Terms of Service as 'anti free speech', just show them this. People use these platforms to influence others to cause dangerous, real life damage. It is the platforms' responsibility to stop it. ",
 'Trying our very best, Kelly. Thank you.',
 "Didn't you lose your shit on Twitter when you had to move to a window seat?",
 "As always, @TwitterSafety is 'working on it'.  ",
 "Sometimes it's gleeful racists. But yes, it's always racists.",
 'Lotta pissed off racists on here right now.',
 "Wonder how psyched the  @beastieboys are that Infowars played 'Sabotage' on this telecast.",
 'Alex Jones selling shitty vitamin supplements and boner pills just after a pre-recorded Roger Stone Legal Fund ad during a Roger Stone interview after he was arrested like four hours ago is pretty much the most 2019 thing ever.',
 'Nice work, Charlie.',
 'In all seriousness, though, this is good news. Social platforms (some of them) are at least beginning to come around to the fact that they are fucking up our society and actively trying to do something about it.',
 'This is going to be hard to implement because conspiracies ARE LITERALLY ALL THEY CURRENTLY RECOMMEND ',
 "LOL!!! Today is literally the four month anniversary of Breitbart asking me to preserve all communications with my friends and family to prepare for a lawsuit. My lawyer requested the same of them, including the communications of Steve Bannon. Wonder why we haven't heard back. ",
 "These guys have totally nailed every decision they've made so far, so we don't see how this could be a problem. ",
 'This is such a good reply and completely spot on. ',
 ' ',
 'White privilege is losing the majority of your advertising dollars, the sole reason you have a show, and still keeping your show. ',
 'Sounds credible. Thanks!',
 "To the founders, these social networks were supposed to be utopias. Ignoring the fact that they're just data-mining money machines, these networks have turned into something they never saw coming. Truth is that these founders are no longer qualified to run what they've now become",
 'Do you have anything like this from a legitimate news source?',
 "Please read this thread. We are locked in to a confluence of awfulness: People game the social networks and break the rules while their founders are loathe to admit there's anything wrong or to take any action. This is why harassment, doxxing and hate will continue unabated. ",
 "Monday's guest on the @TODAYshow: ",
 'STOP THIS YASHAR THE COUNTRY IS ALREADY BROKEN ENOUGH',
 "DISCLAIMER: We don't actually know that.",
 "TRANSLATION: She's getting fired. ",
 "UPDATE: The SLEEPING GIANTS LIST of advertisers dropping Breitbart was updated at 10:30EST. Round number goal achieved! We're up to 4,100, people. Advertisers are still appearing there without their knowledge, so keep up the good work! ",
 "* This commentary was purely about Facebook, not about the politics of the situation, of which we're woefully uninformed about.",
 'This was about Facebook.',
 'Literally the only way Facebook will enforce their Terms of Service on you is to be a dictator. ',
 "Here's the thing...when you've promised yourself you're just going to blindly block all of them no matter what, as I've just done today, everyday is a troll-free day. It's fucking magical!",
 'LOL. Yes.',
 'Really enjoying this troll-free day.',
 "You might not have read the whole thread. Not sure if you're familiar with our mission here.",
 'LOL!!! Working on it! (The store, not the paychecks.)',
 "It's one thing for @TeamYouTube to turn a blind eye to obvious racism on their platform. It's quite another for their algorithm to serve it up to people who aren't even looking for it. What a mess. ",
 "Thanks for your patience. As a writer, it's very hard to ignore the opportunity to try to convince someone that they're wrong or correct their bullshit, but I've realized it can't be done.",
 'FREEEEEEDOMMMM!!!',
 'Giving it a go.',
 'This one was for you, brother.',
 "To deal with our ongoing issues with engaging the trolls, we're going to try something new: BLOCKING THE SHIT OUT OF THEM",
 'You get one, too! BLOCKED!',
 "It doesn't matter. The only thing that matters is that we won't be tempted to engage with him anymore.",
 "Finally said goodbye to our favorite troll today. After a year of bullshitty false equivalence and whining, he went one lie too far. It's been a good run, man. We'll miss you.",
 "The onus is on you. We didn't say anything about her. You call other people liars? That's rich, man. You finally earned yourself a block.",
 'Great job again, @TeamYouTube! ',
 'How about you show us the tweet where we said that?',
 'Advertisers paid for this. ',
 "Moving on, my man. We're not going to solve this one today. Have a good one.",
 'No, you said I deserved to have my kids threatened with death. Also...this is a curious tweet for someone who has such a problem with us.',
 "Right. That is your opinion. I gave you mine. You also gave your opinion that my kids deserved to be threatened with death. What's your address?",
 "Where's the lie? I believe that the kids were disrespectful and they were taunting the Native American man. If my kids had done that, I would have the same opinion of them. But they wouldn't. That's called an opinion, not a lie. What's your address?",
 "I disagree with racism. Strongly. People post screenshots and video on here. That is not slander. None of us have made any money on this. It is a volunteer effort. I have never been in politics, so I have no 'political enemies.' Now...your addresss. What is it?",
 "What's your address and the names of your family? Let's be on equal footing for this debate.",
 'Is that why @reddit allows unfettered hate and sexism on its platform? The software?',
 'Put your address up here, then.',
 'Heyoooo',
 'But, yeah, you could probably get two first round ',
 'Wrong number. ',
 "Only if it's all brunch.",
 "Yeah, not buying the 'it's your fault your kids got death threats' thing from someone who won't even use their real name on here. Blocked.",
 'Other than my kids and wife getting death threats on their phones? No. Have always advocated against harassment and doxxing of anyone. It sucks.',
 "MY kids got doxxed and threatened. You think I'm okay with it??",
 'Thank you. Just very sensitive about calls for violence.',
 'Too everything. Violence is not the answer.',
 'No. Please no. Delete this. Please.',
 'So much exhausting fucking fuckery.',
 "If it's the 'Roman salute', why is it a joke?",
 "These students paid no price for giving an open Nazi salute. Not one was disciplined. Even when there's a clear photo, the waters get muddied on Twitter and that's that. If that's the way it is now, we'll, that's tragic, but the media doesn't need to play into it, too.",
 'Who here wants to be the next guest on the  @TODAYshow?',
 'Damn. Did it again. Sorry, folks. Do not engage the trolls. Do not engage the trolls. Do not engage the trolls. Do not engage the trolls. Do not engage the trolls. Do not engage the trolls. Do not engage the trolls. Do not engage the trolls. Do not engage the trolls. Do not engag ',
 'LOL. He can have the alt-right stardom.',
 "Take the L for what? Stupid tweets from a Richard Spencer acolyte who worked for a website funded by the Koch Brothers. Nah. We're good.",
 'Billionaire backing? Anyone here get a check from a billionaire? Still waiting for ours. ',
 "LOL. You worked for The Daily Caller, which is funded by the Koch Brothers. Are you sure this is the path you'd like to go down?",
 'Put your name up here.',
 "It's called working. You know. You've done it for Richard Spencer. ",
 "It's all about the grift. ",
 "If getting paid by Richard Spencer is edgy, I'm fine to not be edgy.",
 "From the person that wrote 'No Campus For White Men', that is truly an honor.",
 "Hey, at least I don't get paid by Richard Spencer.",
 'You look a little young for Dad humor. ',
 'Did Richard tell you to write that?',
 "Hey, at least we didn't get a paycheck from him like Scotty did.",
 '',
 "Remember when your pal said that 'alt-right is the new punk rock'? Did you write that?",
 "If you were someone being accused of being racist, this dude would probably be the last person you'd want to be defending you. ",

In [19]:
all_nodes, ner_visuals = get_nodes_from_batch(test_sents)

1/1 ━━━━━━━━━━━━━━━━━━━━ 8s 8s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 14s 14s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 16s 16s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 11s 11s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 247ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 22s 11s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 11s 11s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 10s 10s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 10s 10s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 7s 7s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 277ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 283ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 232ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step
3/3 ━━━━━━━━━━━━━━━━━━━━ 11s 5s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
No Relations Found
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
No Relations Found

In [42]:
doc = nlp(test_sents[10])
[(tk,pos) for tk, pos in zip([t.text for t in doc],[t.pos_ for t in doc])]

[('No', 'INTJ'),
 (',', 'PUNCT'),
 ('the', 'DET'),
 ('implication', 'NOUN'),
 (',', 'PUNCT'),
 ('IM', 'PROPN'),
 ('HO', 'PROPN'),
 (',', 'PUNCT'),
 ('is', 'AUX'),
 ('that', 'SCONJ'),
 ('anyone', 'PRON'),
 ('whose', 'DET'),
 ('judgement', 'NOUN'),
 ('allowed', 'VERB'),
 ('them', 'PRON'),
 ('to', 'PART'),
 ('be', 'AUX'),
 ('in', 'ADP'),
 ('that', 'DET'),
 ('photo', 'NOUN'),
 ('can', 'AUX'),
 ('rightfully', 'ADV'),
 ('govern', 'VERB'),
 ('a', 'DET'),
 ('state', 'NOUN'),
 ('that', 'PRON'),
 ('has', 'VERB'),
 ('a', 'DET'),
 ('sizable', 'ADJ'),
 ('(', 'PUNCT'),
 ('or', 'CCONJ'),
 ('really', 'ADV'),
 ('any', 'DET'),
 (')', 'PUNCT'),
 ('population', 'NOUN'),
 ('that', 'PRON'),
 ('holds', 'VERB'),
 ('those', 'DET'),
 ('tropes', 'NOUN'),
 ('to', 'PART'),
 ('be', 'AUX'),
 ('the', 'DET'),
 ('most', 'ADV'),
 ('offensive', 'ADJ'),
 ('there', 'PRON'),
 ('are', 'VERB'),
 ('.', 'PUNCT')]

In [20]:
ner_visuals

                t0               t1               t2  \
0                O                O                O
1             That               is             your
0                O                O                O
1             None               of            these
0                O                O                O
1         Everyone         deserves               to
0                O                O                O
1             2019                :              The
0                O                O                O
1             Real             talk                .
0                O                O                O
1             Okay                ,              how
0                O                O                O
1           Agreed                !              Now
0                O                O                O
1              LOL                !              You
0                O                O                O
1         Reminder             that            there
0                O                O                O
1             That               's             what
0                O                O                O
1               No                ,              the
0                O                O                O
1           Sounds             good                .
0                O                O                O
1             This               is                a
0                O                O                O
1           Plenty               of           people
0                O                O                O
1             When              you             have
0                O                O                O
1               He            might                '
0                O          I-Value                O
1            Great            minds                ,
0                O                O                O
1             Nope                .              You
0                O                O                O
1          Imagine           having              the
0                O                O                O
1               He              did               it
0                O                O                O
1             Okay                ,             more
0         B-Person         I-Person                O
1            Steve             King               is
0                O                O                O
1              Now               go             back
0                O                O                O
1              Not         equating            those
0                O                O                O
1               It               's              not
0                O                O                O
1            There              are             also
0                O                O                O
1            Whole              lot               of
0                O              NaN              NaN
1             2019              NaN              NaN
0                O                O                O
1               He               's              the
0                O                O              NaN
1           Indeed                .              NaN
0                O                O                O
1       DISCLAIMER                :             This
0                O                O                O
1       Apparently               we            haven
0                O                O                O
1              NEW             RULE                :
0                O                O                O
1               Do              not             pass
0                O                O                O
1               To              all               of
0         B-Handle                O                O
1              Gab                :               We
0                O   B-Organization                O
1               Go             Rams                .
0                O                O                O
1              ...              has          nothing
0                O                O                O
1          Welcome             back                .
0                O                O                O
1              Man               oh              man
0                O                O         B-Handle
1             Cool         platform                @
0                O                O                O
1              Wow                .
0                O                O                O
1            Sorry            about              the
0                O                O                O
1              And               if             that
0                O                O                O
1             FREE             IDEA              FOR
0                O                O                O
1            Still          dealing             with
0                O                O                O
1            Happy               to             have
0                O                O                O
1             Good            stuff                .
0                O                O                O
1              And               at             what
0              NaN              NaN              NaN
1              NaN              NaN              NaN
0         B-Person         I-Person                O
1          Kaitlin          Bennett               is
0                O                O                O
1             Wait                ,              how
0                O                O                O
1        CONFIRMED                :                @
0                O                O                O
1           Always               Be         Grifting
0                O                O                O
1             This               is             just
0                O                O                O
1               So      essentially                ,
0                O                O                O
1             Just            today                ,
0                O                O                O
1          Nothing               's             ever
0                O                O                O
1             Wait                ,              you
0                O                O                O
1             This               is              our
0                O                O                O
1             This               is        important
0                O                O                O
1               Ãĥ              âĢļ               ÃĤ
0                O                O                O
1             Lord        Voldemort                .
0                O                O                O
1        CONFIRMED                :                @
0                O                O                O
1        CONFIRMED                :
0                O                O         B-Handle
1        CONFIRMED                :                @
0                O                O                O
1             This               is              the
0                O                O                O
1              And                I           should
0                O                O                O
1                I               'm               an
0                O                O                O
1          Several            years            later
0                O                O                O
1              Man                ,                @
0                O                O                O
1          Imagine              for                a
0              NaN              NaN              NaN
1              NaN              NaN              NaN
0                O         B-Person         I-Person
1             When           Tucker          Carlson
0  B-Virtual Place  B-Virtual Place  B-Virtual Place
1          SureJan                .              gif
0                O                O                O
1               It               's           almost
0                O                O                O
1             This          opinion               is
0                O                O         B-Handle
1        CONFIRMED                :                @
0                O                O                O
1              Who             knew               it
0                O                O                O
1              FIX             YOUR             SHIT
0                O                O         B-Handle
1        CONFIRMED                :                @
0                O                O         I-Person
1       Apparently                ,           Brokaw
0                O                O                O
1              Nah                .
0                O                O                O
1        CONFIRMED                :                @
0                O         B-Handle                O
1              The          Gorilla           Change
0                O                O         B-Handle
1        CONFIRMED                :                @
0                O                O                O
1             This           thread               is
0                O                O                O
1    Unfortunately                ,                @
0                O                O                O
1        Breitbart          printed               an
0                O                O                O
1         Remember             when              you
0                O                O                O
1             Cool                ,              but
0                O                O                O
1            There               's                a
0                O                O                O
1              Why               is               is
0                O                O                O
1        CONFIRMED                :                @
0                O                O         B-Handle
1            Hello                ,                @
0                O                O                O
1        CONFIRMED                :                @
0                O                O                O
1        CONFIRMED                :                @
0                O                O                O
1            Being              off          Twitter
0                O                O                O
1              You              're            right
0                O                O                O
1            Weird                .              The
0                O                O                O
1               No              one          watches
0                O                O                O
1             They          shouldn               't
0   B-Organization                O                O
1      Advertisers             have           always
0                O                O                O
1        According               to             this
0                O                O                O
1             This           person               is
0                O                O                O
1      Advertisers            leave            these
0                O                O                O
1           THREAD                :             This
0                O                O                O
1           Anyone              who        threatens
0                O                O                O
1             When           people             talk
0                O                O                O
1           Trying              our             very
0                O                O                O
1             Didn               't              you
0                O                O                O
1               As           always                ,
0                O                O                O
1        Sometimes               it               's
0                O                O                O
1            Lotta           pissed              off
0                O                O                O
1           Wonder              how          psyched
0         B-Person         I-Person                O
1             Alex            Jones          selling
0                O                O                O
1             Nice             work                ,
0                O                O                O
1               In              all      seriousness
0                O                O                O
1             This               is            going
0                O                O                O
1              LOL              !!!            Today
0                O                O                O
1            These             guys             have
0                O                O                O
1             This               is             such
0                O              NaN              NaN
1                               NaN              NaN
0                O                O                O
1            White        privilege               is
0                O                O                O
1           Sounds         credible                .
0                O                O                O
1               To              the         founders
0                O                O                O
1               Do              you             have
0                O                O                O
1           Please             read             this
0                O                O                O
1           Monday               's            guest
0                O                O         B-Person
1             STOP             THIS           YASHAR
0                O                O                O
1       DISCLAIMER                :               We
0                O                O                O
1      TRANSLATION                :              She
0                O                O                O
1           UPDATE                :              The
0                O                O                O
1                *             This       commentary
0                O                O                O
1             This              was            about
0                O                O                O
1        Literally              the             only
0                O                O                O
1             Here               's              the
0                O                O                O
1              LOL                .              Yes
0                O                O                O
1           Really         enjoying             this
0                O                O                O
1              You            might              not
0                O                O                O
1              LOL              !!!          Working
0                O                O                O
1               It               's              one
0                O                O                O
1           Thanks              for             your
0                O                O              NaN
1   FREEEEEEDOMMMM              !!!              NaN
0                O                O                O
1           Giving               it                a
0                O                O                O
1             This              one              was
0                O                O                O
1               To             deal             with
0                O                O                O
1              You              get              one
0                O                O                O
1               It            doesn               't
0                O                O                O
1          Finally             said          goodbye
0                O                O                O
1              The             onus               is
0                O                O                O
1            Great              job            again
0                O                O                O
1              How            about              you
0   B-Organization                O                O
1      Advertisers             paid              for
0                O                O                O
1           Moving               on                ,
0                O                O                O
1               No                ,              you
0                O                O                O
1            Right                .             That
0                O                O                O
1            Where               's              the
0                O                O                O
1                I         disagree             with
0                O                O                O
1             What               's             your
0                O                O                O
1               Is             that              why
0                O                O                O
1              Put             your          address
0                O              NaN              NaN
1          Heyoooo              NaN              NaN
0                O                O                O
1              But                ,             yeah
0                O                O                O
1            Wrong           number                .
0                O                O                O
1             Only               if               it
0                O                O                O
1             Yeah                ,              not
0                O                O                O
1            Other             than               my
0                O       B-Identity                O
1               MY             kids              got
0                O                O                O
1            Thank              you                .
0                O                O                O
1              Too       everything                .
0                O                O                O
1               No                .           Please
0                O                O                O
1               So             much       exhausting
0                O                O                O
1               If               it               's
0                O                O                O
1            These         students             paid
0                O                O                O
1              Who             here            wants
0                O                O                O
1             Damn                .              Did
0                O                O                O
1              LOL                .               He
0                O                O                O
1             Take              the                L
0                O                O                O
1      Billionaire          backing                ?
0                O                O                O
1              LOL                .              You
0                O                O                O
1              Put             your             name
0                O                O                O
1               It               's           called
0                O                O                O
1               It               's              all
0                O                O                O
1               If          getting             paid
0                O                O                O
1             From              the           person
0                O                O                O
1              Hey                ,               at
0                O                O                O
1              You             look                a
0                O         B-Person                O

In [21]:
all_nodes.loc[all_nodes['pred_rel'] != 'none']

,sid,sentence_text,lefttext,righttext,pred_rel,pred_val
0,7603,"[Steve, King, is, going, to, endorse, Ralph, N...",Steve King,Ralph Northam,Threat,Neutral
0,7952,"[It, 's, not, a, comparison, ., Pointing, out,...",King,racism,Agrees,Negative
1,7952,"[It, 's, not, a, comparison, ., Pointing, out,...",racism,King,Agrees,Negative
0,6155,"[Man, oh, man, ., This, is, real, ., Just, saw...",iTunes,AppleSupport,Is,Neutral
1,6155,"[Man, oh, man, ., This, is, real, ., Just, saw...",AppleSupport,iTunes,Is,Neutral
3,4238,"[Cool, platform, @, Jack, ., ]",.,@,Cooperates,Neutral
4,4238,"[Cool, platform, @, Jack, ., ]",@,,Cooperates,Neutral
5,4238,"[Cool, platform, @, Jack, ., ]",,@,Cooperates,Neutral
2,8782,"[FREE, IDEA, FOR, @, jack, :, Get, rid, of, AL...",@,bots,Present,Neutral
3,8782,"[FREE, IDEA, FOR, @, jack, :, Get, rid, of, AL...",bots,@,Present,Neutral
4,8782,"[FREE, IDEA, FOR, @, jack, :, Get, rid, of, AL...",jack,bots,Present,Neutral
5,8782,"[FREE, IDEA, FOR, @, jack, :, Get, rid, of, AL...",bots,jack,Present,Neutral
8,9707,"[CONFIRMED, :, @, creditsesame, will, no, long...",Tucker,Tonight,Is,Neutral
9,9707,"[CONFIRMED, :, @, creditsesame, will, no, long...",Tonight,Tucker,Is,Neutral
0,2131,"[CONFIRMED, :, @, TSCTA, has, blocked, Breitba...",TSCTA,Breitbart,Is,Positive
1,2131,"[CONFIRMED, :, @, TSCTA, has, blocked, Breitba...",Breitbart,TSCTA,Is,Positive
3,8355,"[CONFIRMED, :, @, baronfig, has, blocked, Brei...",Breitbart,@,Caused,Positive
4,8355,"[CONFIRMED, :, @, baronfig, has, blocked, Brei...",baronfig,Breitbart,Is,Positive
5,8355,"[CONFIRMED, :, @, baronfig, has, blocked, Brei...",Breitbart,baronfig,Is,Positive
0,9985,"[I, 'm, an, advertising, executive, and, most,...",advertising executive,journalists,Cooperates,Positive
1,9985,"[I, 'm, an, advertising, executive, and, most,...",journalists,advertising executive,Cooperates,Positive
2,8797,"[CONFIRMED, :, @, CaciqueInc, has, blocked, Br...",@,Breitbart,Caused,Positive
3,8797,"[CONFIRMED, :, @, CaciqueInc, has, blocked, Br...",Breitbart,@,Caused,Positive
4,8797,"[CONFIRMED, :, @, CaciqueInc, has, blocked, Br...",CaciqueInc,Breitbart,Caused,Positive
5,8797,"[CONFIRMED, :, @, CaciqueInc, has, blocked, Br...",Breitbart,CaciqueInc,Caused,Positive
4,9110,"[CONFIRMED, :, @, kpthrive, (, Kaiser, Permane...",@,Breitbart,Caused,Positive
5,9110,"[CONFIRMED, :, @, kpthrive, (, Kaiser, Permane...",Breitbart,@,Caused,Positive
8,9110,"[CONFIRMED, :, @, kpthrive, (, Kaiser, Permane...",kpthrive,Breitbart,Caused,Positive
9,9110,"[CONFIRMED, :, @, kpthrive, (, Kaiser, Permane...",Breitbart,kpthrive,Caused,Positive
10,9110,"[CONFIRMED, :, @, kpthrive, (, Kaiser, Permane...",Kaiser Permanente,Breitbart,Is,Positive
11,9110,"[CONFIRMED, :, @, kpthrive, (, Kaiser, Permane...",Breitbart,Kaiser Permanente,Is,Positive
0,9822,"[CONFIRMED, :, @, GustoHQ, has, blocked, Breit...",GustoHQ,Breitbart,Is,Positive
1,9822,"[CONFIRMED, :, @, GustoHQ, has, blocked, Breit...",Breitbart,GustoHQ,Is,Positive
8,8747,"[Advertisers, leave, these, shows, because, ma...",brands,immigrants,Threat,Positive
9,8747,"[Advertisers, leave, these, shows, because, ma...",immigrants,brands,Threat,Positive
0,7149,"[When, people, talk, about, the, social, platf...",Terms,anti free speech,MovesFor,Negative
1,7149,"[When, people, talk, about, the, social, platf...",anti free speech,Terms,MovesFor,Negative
0,2014,"[Sometimes, it, 's, gleeful, racists, ., But, ...",racists,racists,Cooperates,Positive
1,2014,"[Sometimes, it, 's, gleeful, racists, ., But, ...",racists,racists,Cooperates,Positive
0,9299,"[Wonder, how, psyched, the, , @, beastieboys, ...",beastieboys,Infowars,Cooperates,Negative
1,9299,"[Wonder, how, psyched, the, , @, beastieboys, ...",Infowars,beastieboys,Cooperates,Negative
0,1045,"[It, 's, one, thing, for, @, TeamYouTube, to, ...",@,TeamYouTube,Cooperates,none
1,1045,"[It, 's, one, thing, for, @, TeamYouTube, to, ...",TeamYouTube,@,Cooperates,none
8,7470,"[I, disagree, with, racism, ., Strongly, ., Pe...",.,.,Harms,Neutral
9,7470,"[I, disagree, with, racism, ., Strongly, ., Pe...",.,.,Harms,Neutral
18,7470,"[I, disagree, with, racism, ., Strongly, ., Pe...",.,.,Is,Neutral
19,7470,"[I, disagree, with, racism, ., Strongly, ., Pe...",.,.,Is,Neutral
0,1921,"[Take, the, L, for, what, ?, Stupid, tweets, f...",Richard Spencer,Koch Brothers,Is,Neutral
1,1921,"[Take, the, L, for, what, ?, Stupid, tweets, f...",Koch Brothers,Richard Spencer,Is,Neutral
0,1838,"[LOL, ., You, worked, for, The, Daily, Caller,...",The,Daily Caller,Is,Neutral
1,1838,"[LOL, ., You, worked, for, The, Daily, Caller,...",Daily Caller,The,Is,Neutral
2,1838,"[LOL, ., You, worked, for, The, Daily, Caller,...",The,Koch Brothers,Is,Neutral
3,1838,"[LOL, ., You, worked, for, The, Daily, Caller,...",Koch Brothers,The,Is,Neutral
4,1838,"[LOL, ., You, worked, for, The, Daily, Caller,...",Daily Caller,Koch Brothers,Is,Neutral
5,1838,"[LOL, ., You, worked, for, The, Daily, Caller,...",Koch Brothers,Daily Caller,Is,Neutral
1,7243,"[From, the, person, that, wrote, ', No, Campus...",White,Campus,Cooperates,Positive
2,7243,"[From, the, person, that, wrote, ', No, Campus...",Campus,Men,Cooperates,Positive
3,7243,"[From, the, person, that, wrote, ', No, Campus...",Men,Campus,Cooperates,Positive
6,9386,"[., @, NBCNews, and, @, SavannahGuthrie, shoul...",NBCNews,@,Is,Neutral
7,9386,"[., @, NBCNews, and, @, SavannahGuthrie, shoul...",@,NBCNews,Is,Neutral
4,7082,"[Whether, or, not, ', the, whole, story, was, ...",racist,kids,Cooperates,Negative
5,7082,"[Whether, or, not, ', the, whole, story, was, ...",kids,racist,Cooperates,Negative
1,2771,"[Get, his, name, out, of, your, mouth, ,, Corn...",Corn,mouth,Cooperates,none
2,2771,"[Get, his, name, out, of, your, mouth, ,, Corn...",mouth,Hitler,Cooperates,Neutral
3,2771,"[Get, his, name, out, of, your, mouth, ,, Corn...",Hitler,mouth,Cooperates,Neutral
0,7529,"[You, 're, right, ,, Peter, ., It, 's, totally...",Peter,kids,Disagrees,Negative
1,7529,"[You, 're, right, ,, Peter, ., It, 's, totally...",kids,Peter,Disagrees,Negative
0,5455,"[Hey, ,, he, has, a, right, to, be, angry, at,...",angry,Jordan,Present,Negative
1,5455,"[Hey, ,, he, has, a, right, to, be, angry, at,...",Jordan,angry,Present,Negative